language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

before_install:
    - pip install pip -U
    - pip install setuptools -U

script:
    - pip install -e .
    - python -B -m unittest discover -s test

notifications:
    email:
        on_success: change
        on_failure: always
