language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

cript:
    - python setup.py sdist
    - pip install --no-use-wheel --no-deps dist/*.tar.gz
    - python -B -m unittest discover -s test

notifications:
    email:
        on_success: change
        on_failure: always
